import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const DEFAULT_CHECKLIST = [
  { id: 'application', label: 'Candidatura enviada', completed: false },
  { id: 'docs', label: 'Documentos traduzidos', completed: false },
  { id: 'acceptance', label: 'Carta de aceitação recebida', completed: false },
  { id: 'passport', label: 'Passaporte válido', completed: false },
  { id: 'visa', label: 'Visto solicitado', completed: false },
  { id: 'insurance', label: 'Seguro contratado', completed: false },
  { id: 'housing', label: 'Alojamento confirmado', completed: false },
  { id: 'flight', label: 'Passagem comprada', completed: false },
  { id: 'courses', label: 'Disciplinas aprovadas', completed: false },
  { id: 'financial', label: 'Plano financeiro fechado', completed: false },
  { id: 'bank', label: 'Conta internacional aberta', completed: false },
  { id: 'chip', label: 'Chip/internet internacional', completed: false },
];

async function main() {
  console.log('Seeding database...');

  // Check if data already exists
  const count = await prisma.universityOption.count();
  if (count > 0) {
    console.log(`Database already has ${count} universities. Skipping seed.`);
    return;
  }

  // Seed Universities
  await prisma.universityOption.createMany({
    data: [
      {
        id: 'unitn',
        universityName: 'Università di Trento',
        city: 'Trento',
        country: 'Itália',
        countryCode: 'IT',
        latitude: 46.0677,
        longitude: 11.1501,
        programArea: 'STEM',
        stemFocus: ['Engenharia', 'Ciências da Computação', 'Física', 'Matemática'],
        exchangeDurationMonths: 6,
        websiteUrl: 'https://www.unitn.it',
        departmentUrl: 'https://www.unitn.it/en/study/international-students',
        languageOfInstruction: ['Italiano', 'Inglês'],
        localLanguage: ['Italiano'],
        cityType: 'small',
        estimatedMonthlyCost: {
          housing: 450,
          food: 220,
          transport: 45,
          internetPhone: 20,
          studyMaterials: 50,
          leisure: 150,
          healthInsurance: 30,
          misc: 80,
          total: 1045,
          currency: 'EUR',
        },
        housingOptions: [
          {
            type: 'university_residence',
            minPrice: 250,
            maxPrice: 450,
            currency: 'EUR',
            notes: 'Residência universitária com demanda moderada',
          },
          {
            type: 'shared_room',
            minPrice: 300,
            maxPrice: 500,
            currency: 'EUR',
            notes: 'Quartos compartilhados no centro',
          },
        ],
        academicProfile: {
          stemStrengthScore: 8.0,
          researchOpportunityScore: 8.0,
          labInfrastructureScore: 8.0,
          industryConnectionScore: 7.0,
          workOpportunityScore: 6.0,
          internshipPotentialScore: 6.0,
        },
        lifeProfile: {
          qualityOfLifeScore: 8.0,
          safetyScore: 9.0,
          studentLifeScore: 7.0,
          adaptationEaseScore: 6.0,
          climatePreferenceScore: 7.0,
          publicTransportScore: 7.0,
        },
        userPreferencesFit: {
          budgetFitScore: 7.5,
          languageFitScore: 5.0,
          careerFitScore: 7.0,
          overallFitScore: 7.5,
        },
        status: 'shortlisted',
        priorityTag: 'A',
        pros: [
          'Excelente reputação em Ciências e Engenharia',
          'Custo de vida relativamente baixo para Itália',
          'Cidade segura, compacta e bonita',
          'Boa oferta de disciplinas em inglês',
          'Próximo a Áustria e Suíça (viagens baratas)',
        ],
        cons: [
          'Italiano necessário para vida cotidiana',
          'Inverno frio',
          'Cidade pequena (limitada para networking)',
        ],
        redFlags: [],
        personalNotes:
          'Trento é a minha primeira opção no momento. A universidade tem ótima reputação em STEM e o custo de vida é razoável. Preciso melhorar meu italiano básico antes de ir.',
        links: [
          { label: 'Site oficial', url: 'https://www.unitn.it/en' },
          { label: 'Programa internacional', url: 'https://www.unitn.it/en/study/international-students' },
        ],
        deadlines: [
          { label: 'Application deadline', date: '2026-03-15', type: 'application' },
          { label: 'Visto', date: '2026-05-01', type: 'visa' },
          { label: 'Alojamento', date: '2026-04-01', type: 'housing' },
        ],
        checklist: DEFAULT_CHECKLIST.map((item) => ({
          ...item,
          completed: ['application', 'passport'].includes(item.id),
        })),
        createdAt: new Date('2026-01-05T10:00:00Z'),
        updatedAt: new Date('2026-02-10T14:30:00Z'),
      },
      {
        id: 'uc',
        universityName: 'Universidade de Coimbra',
        city: 'Coimbra',
        country: 'Portugal',
        countryCode: 'PT',
        latitude: 40.2033,
        longitude: -8.4103,
        programArea: 'STEM',
        stemFocus: ['Engenharia Informática', 'Ciências', 'Matemática'],
        exchangeDurationMonths: 6,
        websiteUrl: 'https://www.uc.pt',
        departmentUrl: 'https://www.uc.pt/en',
        languageOfInstruction: ['Português', 'Inglês'],
        localLanguage: ['Português'],
        cityType: 'medium',
        estimatedMonthlyCost: {
          housing: 380,
          food: 180,
          transport: 35,
          internetPhone: 15,
          studyMaterials: 40,
          leisure: 120,
          healthInsurance: 25,
          misc: 60,
          total: 855,
          currency: 'EUR',
        },
        housingOptions: [
          {
            type: 'university_residence',
            minPrice: 150,
            maxPrice: 300,
            currency: 'EUR',
            notes: 'Residências universitárias com preços acessíveis',
          },
          {
            type: 'shared_room',
            minPrice: 250,
            maxPrice: 400,
            currency: 'EUR',
            notes: 'Quartos no centro histórico',
          },
        ],
        academicProfile: {
          stemStrengthScore: 7.0,
          researchOpportunityScore: 7.0,
          labInfrastructureScore: 7.0,
          industryConnectionScore: 5.5,
          workOpportunityScore: 5.0,
          internshipPotentialScore: 5.0,
        },
        lifeProfile: {
          qualityOfLifeScore: 7.0,
          safetyScore: 8.0,
          studentLifeScore: 8.5,
          adaptationEaseScore: 9.5,
          climatePreferenceScore: 8.0,
          publicTransportScore: 6.0,
        },
        userPreferencesFit: {
          budgetFitScore: 9.0,
          languageFitScore: 10.0,
          careerFitScore: 5.5,
          overallFitScore: 7.0,
        },
        status: 'interested',
        priorityTag: 'B',
        pros: [
          'Sem barreira de idioma — Português!',
          'Custo de vida muito baixo',
          'Cidade universitária vibrante',
          'Alta compatibilidade de créditos',
          'Voo barato do Brasil',
        ],
        cons: [
          'Ecossistema de startups fraco',
          'Reputação STEM menor que Trento ou FEUP',
          'Oportunidades de trabalho limitadas',
        ],
        redFlags: [],
        personalNotes:
          'Boa opção de backup. Idioma é uma vantagem enorme. Mas prefiro ambientes com mais inovação.',
        links: [{ label: 'Site oficial', url: 'https://www.uc.pt/en' }],
        deadlines: [
          { label: 'Application deadline', date: '2026-04-30', type: 'application' },
          { label: 'Alojamento', date: '2026-05-15', type: 'housing' },
        ],
        checklist: DEFAULT_CHECKLIST.map((item) => ({ ...item })),
        createdAt: new Date('2026-01-20T09:00:00Z'),
        updatedAt: new Date('2026-01-20T09:00:00Z'),
      },
      {
        id: 'feup',
        universityName: 'Faculdade de Engenharia da Universidade do Porto',
        city: 'Porto',
        country: 'Portugal',
        countryCode: 'PT',
        latitude: 41.178,
        longitude: -8.598,
        programArea: 'STEM',
        stemFocus: ['Engenharia Informática', 'Engenharia Eletrotécnica', 'Eng. Mecânica', 'Eng. Civil'],
        exchangeDurationMonths: 6,
        websiteUrl: 'https://sigarra.up.pt/feup',
        departmentUrl: 'https://sigarra.up.pt/feup/en/web_page.inicial',
        languageOfInstruction: ['Português', 'Inglês'],
        localLanguage: ['Português'],
        cityType: 'large',
        estimatedMonthlyCost: {
          housing: 430,
          food: 195,
          transport: 40,
          internetPhone: 15,
          studyMaterials: 45,
          leisure: 140,
          healthInsurance: 30,
          misc: 70,
          total: 965,
          currency: 'EUR',
        },
        housingOptions: [
          {
            type: 'university_residence',
            minPrice: 180,
            maxPrice: 350,
            currency: 'EUR',
            notes: 'Residência universitária com alta demanda — lista de espera grande',
          },
          {
            type: 'shared_room',
            minPrice: 300,
            maxPrice: 500,
            currency: 'EUR',
            notes: 'Quartos compartilhados perto do campus',
          },
        ],
        academicProfile: {
          stemStrengthScore: 9.0,
          researchOpportunityScore: 8.0,
          labInfrastructureScore: 9.0,
          industryConnectionScore: 7.5,
          workOpportunityScore: 7.0,
          internshipPotentialScore: 7.0,
        },
        lifeProfile: {
          qualityOfLifeScore: 8.0,
          safetyScore: 8.0,
          studentLifeScore: 8.0,
          adaptationEaseScore: 9.0,
          climatePreferenceScore: 8.0,
          publicTransportScore: 8.0,
        },
        userPreferencesFit: {
          budgetFitScore: 7.0,
          languageFitScore: 10.0,
          careerFitScore: 7.5,
          overallFitScore: 8.0,
        },
        status: 'shortlisted',
        priorityTag: 'A',
        pros: [
          'Top em Engenharia em Portugal e ótima reputação europeia',
          'Sem barreira de idioma',
          'Porto tem forte ecossistema de startups e tech',
          'Cidade vibrante, boa vida social',
          'Boa compatibilidade de créditos',
        ],
        cons: [
          'Aluguel subindo (gentrificação)',
          'Campus um pouco distante do centro',
          'Carga acadêmica pesada',
        ],
        redFlags: ['Residência universitária com lista de espera grande'],
        personalNotes:
          'FEUP é a opção mais forte em Engenharia. Porto tem tudo: startup ecosystem, qualidade de vida, idioma familiar. Maior preocupação é conseguir residência universitária.',
        links: [
          { label: 'FEUP', url: 'https://sigarra.up.pt/feup/en/web_page.inicial' },
          { label: 'Programa internacional', url: 'https://www.up.pt/portal/en/students/international/' },
        ],
        deadlines: [
          { label: 'Application deadline', date: '2026-03-01', type: 'application' },
          { label: 'Alojamento', date: '2026-03-15', type: 'housing' },
        ],
        checklist: DEFAULT_CHECKLIST.map((item) => ({
          ...item,
          completed: ['application', 'passport', 'financial'].includes(item.id),
        })),
        createdAt: new Date('2025-12-01T08:00:00Z'),
        updatedAt: new Date('2026-02-14T16:00:00Z'),
      },
      {
        id: 'tub',
        universityName: 'Technische Universität Berlin',
        city: 'Berlim',
        country: 'Alemanha',
        countryCode: 'DE',
        latitude: 52.5118,
        longitude: 13.3265,
        programArea: 'STEM',
        stemFocus: ['Engenharia', 'Ciências da Computação', 'Engenharia Elétrica', 'Física'],
        exchangeDurationMonths: 6,
        websiteUrl: 'https://www.tu.berlin',
        departmentUrl: 'https://www.tu.berlin/en/',
        languageOfInstruction: ['Alemão', 'Inglês'],
        localLanguage: ['Alemão'],
        cityType: 'capital',
        estimatedMonthlyCost: {
          housing: 750,
          food: 280,
          transport: 90,
          internetPhone: 25,
          studyMaterials: 60,
          leisure: 200,
          healthInsurance: 40,
          misc: 100,
          total: 1545,
          currency: 'EUR',
        },
        housingOptions: [
          {
            type: 'university_residence',
            minPrice: 300,
            maxPrice: 500,
            currency: 'EUR',
            notes: 'Studierendenwerk — lista de espera de meses',
          },
          {
            type: 'shared_room',
            minPrice: 500,
            maxPrice: 800,
            currency: 'EUR',
            notes: 'WG (Wohngemeinschaft) — competitivo',
          },
        ],
        academicProfile: {
          stemStrengthScore: 10.0,
          researchOpportunityScore: 10.0,
          labInfrastructureScore: 10.0,
          industryConnectionScore: 9.0,
          workOpportunityScore: 9.0,
          internshipPotentialScore: 9.0,
        },
        lifeProfile: {
          qualityOfLifeScore: 8.0,
          safetyScore: 8.0,
          studentLifeScore: 9.5,
          adaptationEaseScore: 6.0,
          climatePreferenceScore: 5.0,
          publicTransportScore: 10.0,
        },
        userPreferencesFit: {
          budgetFitScore: 4.0,
          languageFitScore: 5.0,
          careerFitScore: 9.5,
          overallFitScore: 7.0,
        },
        status: 'interested',
        priorityTag: 'B',
        pros: [
          'Uma das melhores universidades técnicas do mundo',
          'Berlim = ecossistema de startups líder na Europa',
          'Enorme comunidade internacional',
          'Oportunidades de estágio e networking incomparáveis',
          'Metrô e transporte público excelente',
        ],
        cons: [
          'Custo de vida alto e crescente',
          'Alemão importante para vida social e trabalho',
          'Inverno muito frio',
          'Burocracia alemã pode ser desafiadora',
        ],
        redFlags: ['Mercado de aluguel muito competitivo'],
        personalNotes:
          'Berlim seria incrível para carreira em tech, mas o custo alto e o alemão são barreiras. Vale como opção se receber bolsa boa.',
        links: [{ label: 'Site oficial', url: 'https://www.tu.berlin/en/' }],
        deadlines: [
          { label: 'Application deadline', date: '2026-05-31', type: 'application' },
          { label: 'Alojamento', date: '2026-06-01', type: 'housing' },
        ],
        checklist: DEFAULT_CHECKLIST.map((item) => ({ ...item })),
        createdAt: new Date('2026-02-01T11:00:00Z'),
        updatedAt: new Date('2026-02-01T11:00:00Z'),
      },
      {
        id: 'polimi',
        universityName: 'Politecnico di Milano',
        city: 'Milão',
        country: 'Itália',
        countryCode: 'IT',
        latitude: 45.4786,
        longitude: 9.2273,
        programArea: 'STEM',
        stemFocus: ['Engenharia', 'Design', 'Arquitetura', 'Ciências da Computação'],
        exchangeDurationMonths: 6,
        websiteUrl: 'https://www.polimi.it',
        departmentUrl: 'https://www.polimi.it/en/',
        languageOfInstruction: ['Italiano', 'Inglês'],
        localLanguage: ['Italiano'],
        cityType: 'large',
        estimatedMonthlyCost: {
          housing: 900,
          food: 280,
          transport: 80,
          internetPhone: 20,
          studyMaterials: 60,
          leisure: 220,
          healthInsurance: 40,
          misc: 100,
          total: 1700,
          currency: 'EUR',
        },
        housingOptions: [
          {
            type: 'university_residence',
            minPrice: 400,
            maxPrice: 700,
            currency: 'EUR',
            notes: 'Residência do Politecnico — poucas vagas',
          },
          {
            type: 'private_room',
            minPrice: 700,
            maxPrice: 1100,
            currency: 'EUR',
            notes: 'Quarto privado em Milão é caro',
          },
        ],
        academicProfile: {
          stemStrengthScore: 10.0,
          researchOpportunityScore: 9.0,
          labInfrastructureScore: 9.0,
          industryConnectionScore: 9.0,
          workOpportunityScore: 8.0,
          internshipPotentialScore: 8.0,
        },
        lifeProfile: {
          qualityOfLifeScore: 7.0,
          safetyScore: 7.0,
          studentLifeScore: 7.5,
          adaptationEaseScore: 5.5,
          climatePreferenceScore: 6.0,
          publicTransportScore: 9.0,
        },
        userPreferencesFit: {
          budgetFitScore: 3.0,
          languageFitScore: 5.0,
          careerFitScore: 8.5,
          overallFitScore: 6.0,
        },
        status: 'interested',
        priorityTag: 'C',
        pros: [
          'Top 1 em Engenharia na Itália',
          'Ótimas conexões com indústria',
          'Milão = hub de negócios e tecnologia',
          'Muita diversidade internacional',
        ],
        cons: [
          'Custo de vida mais alto da lista',
          'Aluguel caríssimo em Milão',
          'Italiano importante fora da universidade',
          'Clima neblinoso no inverno',
        ],
        redFlags: ['Custo muito alto pode inviabilizar sem bolsa robusta'],
        personalNotes:
          'PoliMi é impressionante mas o custo de Milão assusta. Precisa de bolsa ou renda extra para ser viável.',
        links: [{ label: 'Site oficial', url: 'https://www.polimi.it/en/' }],
        deadlines: [
          { label: 'Application deadline', date: '2026-04-01', type: 'application' },
          { label: 'Visto', date: '2026-05-15', type: 'visa' },
          { label: 'Alojamento', date: '2026-04-15', type: 'housing' },
        ],
        checklist: DEFAULT_CHECKLIST.map((item) => ({ ...item })),
        createdAt: new Date('2026-02-15T10:00:00Z'),
        updatedAt: new Date('2026-02-15T10:00:00Z'),
      },
    ],
  });

  // Seed Comparison Presets
  await prisma.comparisonPreset.createMany({
    data: [
      {
        id: 'cost-focused',
        name: 'Prioridade: Custo',
        weights: {
          cost: 35,
          housing: 20,
          stemStrength: 15,
          workOpportunity: 10,
          adaptation: 10,
          qualityOfLife: 5,
          studentLife: 5,
        },
      },
      {
        id: 'stem-focused',
        name: 'Prioridade: STEM',
        weights: {
          cost: 10,
          housing: 5,
          stemStrength: 35,
          workOpportunity: 20,
          adaptation: 10,
          qualityOfLife: 10,
          studentLife: 10,
        },
      },
      {
        id: 'career-focused',
        name: 'Prioridade: Carreira',
        weights: {
          cost: 10,
          housing: 5,
          stemStrength: 20,
          workOpportunity: 35,
          adaptation: 10,
          qualityOfLife: 10,
          studentLife: 10,
        },
      },
      {
        id: 'balanced',
        name: 'Equilibrado',
        weights: {
          cost: 15,
          housing: 15,
          stemStrength: 15,
          workOpportunity: 15,
          adaptation: 15,
          qualityOfLife: 15,
          studentLife: 10,
        },
      },
    ],
  });

  // Seed Decision Scenarios
  await prisma.decisionScenario.createMany({
    data: [
      {
        id: 'scholarship-residence',
        name: 'Com bolsa + residência universitária',
        scholarshipAmountMonthly: 300,
        currency: 'EUR',
        housingAdjustment: -150,
        partTimeIncomeMonthly: 0,
        notes: 'Cenário assumindo que consegue bolsa e vaga na residência universitária',
      },
      {
        id: 'part-time-work',
        name: 'Com trabalho part-time',
        scholarshipAmountMonthly: 0,
        currency: 'EUR',
        housingAdjustment: 0,
        partTimeIncomeMonthly: 500,
        notes: 'Cenário trabalhando 20h/semana em emprego local',
      },
      {
        id: 'minimum-budget',
        name: 'Orçamento mínimo',
        scholarshipAmountMonthly: 0,
        currency: 'EUR',
        housingAdjustment: -200,
        partTimeIncomeMonthly: 0,
        notes: 'Cenário com residência barata, sem bolsa, sem renda extra',
      },
    ],
  });

  console.log('Seed completed successfully!');
  console.log('- 5 universities');
  console.log('- 4 comparison presets');
  console.log('- 3 decision scenarios');
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
